#!/bin/bash -e

# Get the username for UID 1000
FIRST_USER_NAME=$(awk -v val=1000 -F ":" '$3==val{print $1}' /etc/passwd)

# Replace the unique number placeholder in the settings.json file
UNIQUENUMBER=$(shuf -i 100000-999999 -n 1)
sed -i -e "s/123456/${UNIQUENUMBER}/" "/home/${FIRST_USER_NAME}/.signalk/settings.json"

# If the script exists in /usr/sbin, remove it
if [ -f /usr/sbin/set-signalk-unique-number ]; then
  rm /usr/sbin/set-signalk-unique-number
fi

# Likewise, if the service file exists in /etc/systemd/system, disable and remove it.
# I had trouble getting ConditionFirstBoot to work but this has the same effect.
if [ -f /etc/systemd/system/set-signalk-unique-number.service ]; then
  systemctl disable set-signalk-unique-number
  rm /etc/systemd/system/set-signalk-unique-number.service
fi
