name: OpenPlotter-HALPI CI Build

run-name: |
  ${{ github.event_name == 'push' && format('🌱 Push build - {0}', github.event.head_commit.message) || '' }}
  ${{ github.event_name == 'pull_request' && format('👷 PR #{0} build - {1}', github.event.pull_request.number, github.event.pull_request.title) || '' }}

on:
  workflow_call:
    inputs:
      upload_artifact:
        required: true
        type: boolean
        description: "Upload artifact after build"

env:
  PLATFORM: bookworm

jobs:
  image-builder:
    name: "OpenPlotter-HALPI (${{ matrix.pi-gen.architecture }})"
    runs-on: ubuntu-latest-arm64
    strategy:
      fail-fast: false
      matrix:
        pi-gen: [
          { branch: arm64,  architecture: arm64 }
        ]

    steps:
      - name: ⬇ Checkout OpenPlotter-HALPI
        uses: actions/checkout@v4

      - name: ⬇ Checkout pi-gen
        uses: actions/checkout@v4
        with:
          repository: RPi-Distro/pi-gen
          ref: ${{ matrix.pi-gen.branch }}
          path: pi-gen

      - name: 🔧 Prepare
        run: |
          sudo apt-get update && sudo apt-get install -y coreutils quilt parted qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc kmod kpartx arch-test xxd pigz
          echo "OPENPLOTTER=OpenPlotter-HALPI-${{ env.PLATFORM }}-${{ matrix.pi-gen.architecture }}" >> $GITHUB_ENV

      - name: 👷 Build
        run: |
          cp -R stage-* pi-gen/
          touch pi-gen/stage5/SKIP
          touch pi-gen/stage{2,4,-openplotter}/SKIP_IMAGES
          touch pi-gen/stage-halpi/EXPORT_IMAGE
          cp config pi-gen/ && cd pi-gen
          echo "RELEASE='${{ env.PLATFORM }}'" >> "./config"
          sudo IMG_FILENAME=${{ env.OPENPLOTTER }} ARCHIVE_FILENAME=${{ env.OPENPLOTTER }} ./build-docker.sh

      - name: 📦 Upload
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OPENPLOTTER }}
          path: pi-gen/deploy/*.zip
          retention-days: 3
