name: OpenPlotter-HALPI CI Release

on:
  push:
    tags:
      - 'v*'

jobs:
  github_publish:
    name: 🚀 Publish GitHub Releases
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout OpenPlotter-HALPI
        uses: actions/checkout@v4

      - name: 💾 Artifact download
        uses: actions/download-artifact@v4.1.8
        with:
          pattern: OpenPlotter-HALPI-*
          path: all-artifacts
          merge-multiple: true

      #- name: Delete previous OpenPlotter-HALPI Release
      #  uses: dev-drprasad/delete-older-releases@v0.3.4
      #  with:
      #    keep_latest: 0
      #    delete_tags: true
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release and upload image
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: all-artifacts/*
          tag: OpenPlotter-HALPI
          release_name: OpenPlotter-HALPI
          overwrite: true
          body: |
            ${{ steps.read_template.outputs.RELEASE_BODY }}
