name: OpenPlotter-HALPI CI Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_image:
    name: "OpenPlotter-HALPI (${{ matrix.pi-gen.architecture }})"
    strategy:
      fail-fast: false
      matrix:
        pi-gen: [
          { branch: arm64,  architecture: arm64 }
        ]
    uses: ./.github/workflows/_build_image.yml
    with:
      upload_artifact: true
    secrets: inherit

  github_publish:
    name: 🚀 Publish GitHub Releases
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout OpenPlotter-HALPI
        uses: actions/checkout@v4

      - name: 💾 Artifact download
        uses: actions/download-artifact@v4.1.8
        with:
          pattern: OpenPlotter-HALPI-*
          path: all-artifacts
          merge-multiple: true

      - name: Create release and upload image
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: all-artifacts/*
          draft: true
