name: HALPI OS CI Release

on:
  push:
    branches:
      - 'main'
    # Optionally, you can also trigger on tags if you want
    # tags:
    #   - 'v*'
  workflow_dispatch:

jobs:
  github_publish:
    name: 🚀 Draft GitHub Releases
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Checkout HALPI OS image repository
        uses: actions/checkout@v4

      - name: 🔎 Find latest successful workflow run ID for pull_request.yml
        id: find_run
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'pull_request.yml',
              status: 'success',
              branch: 'main'
            });
            if (!runs.data.workflow_runs.length) {
              throw new Error('No successful workflow runs found for pull_request.yml');
            }
            core.setOutput('run_id', runs.data.workflow_runs[0].id);

      - name: 💾 Download build artifacts from last successful pull_request.yml run
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: all-artifacts
          merge-multiple: true
          run-id: ${{ steps.find_run.outputs.run_id }}

      - name: Create draft GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: all-artifacts/*
          draft: true
